# Generated by Django 5.2.1 on 2025-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
