# Generated by Django 5.2.1 on 2025-05-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
    ]
