# Generated by Django 5.2.1 on 2025-05-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='star_rating',
            field=models.CharField(blank=True, choices=[('5 yulduzli', '5 yulduzli'), ('4 yulduzli', '4 yulduzli'), ('3 yulduzli', '3 yulduzli'), ('2 yulduzli', '2 yulduzli')], max_length=15, null=True, verbose_name='Yulduzlar soni'),
        ),
    ]
