# Generated by Django 5.2.4 on 2025-07-27 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_generalimage_general_alter_helper_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalimage',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.helper'),
        ),
    ]
