# Generated by Django 5.2.1 on 2025-05-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_general_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='star_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, '5 yulduzli'), (4, '4 yulduzli'), (3, '3 yulduzli'), (2, '2 yulduzli')], null=True, verbose_name='Yulduzlar soni'),
        ),
    ]
