# Generated by Django 5.2.4 on 2025-08-08 15:03

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_generalimage_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='general',
            name='region',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.region'),
            preserve_default=False,
        ),
    ]
