# Generated by Django 5.2.4 on 2025-08-09 07:00

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_general_city_alter_general_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='region', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.city'),
        ),
        migrations.AlterField(
            model_name='general',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.region'),
        ),
    ]
