# Generated by Django 5.2.1 on 2025-07-15 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_ln_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='general',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.region'),
        ),
    ]
